[package]
name = "rust_lib_whitenoise"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.10.0"
whitenoise = { version = "0.1.0", git = "https://github.com/parres-hq/whitenoise", rev = "1c997dff04248550ca388282c91dd3aeaf7b883f" }
tokio = { version = "1.44", features = ["rt", "rt-multi-thread"] }
serde_json = "1.0.140"
hex = "0.4"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[lints.clippy]
not_unsafe_ptr_arg_deref = "allow"
