[package]
name = "rust_lib_whitenoise"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.10.0"
whitenoise = { version = "0.1.0", git = "https://github.com/parres-hq/whitenoise", rev = "350475ffcd54965cac98caad5f5ac5a213199389" }
tokio = { version = "1.44", features = ["rt", "rt-multi-thread"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
