// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

/// Gets all visible AccountGroups for the given account.
/// Visible means: pending or accepted (not declined).
Future<List<AccountGroup>> visibleAccountGroups({
  required String accountPubkey,
}) => RustLib.instance.api.crateApiAccountGroupsVisibleAccountGroups(
  accountPubkey: accountPubkey,
);

/// Gets all pending AccountGroups for the given account.
/// Pending means the user hasn't yet accepted or declined.
Future<List<AccountGroup>> pendingAccountGroups({
  required String accountPubkey,
}) => RustLib.instance.api.crateApiAccountGroupsPendingAccountGroups(
  accountPubkey: accountPubkey,
);

/// Gets a specific AccountGroup by account and group ID.
Future<AccountGroup?> getAccountGroup({
  required String accountPubkey,
  required String mlsGroupId,
}) => RustLib.instance.api.crateApiAccountGroupsGetAccountGroup(
  accountPubkey: accountPubkey,
  mlsGroupId: mlsGroupId,
);

/// Accepts a group invite by setting user_confirmation to true.
/// The group will remain visible in the UI.
Future<AccountGroup> acceptAccountGroup({
  required String accountPubkey,
  required String mlsGroupId,
}) => RustLib.instance.api.crateApiAccountGroupsAcceptAccountGroup(
  accountPubkey: accountPubkey,
  mlsGroupId: mlsGroupId,
);

/// Declines a group invite by setting user_confirmation to false.
/// The group will be hidden from the UI but remains in MLS.
Future<AccountGroup> declineAccountGroup({
  required String accountPubkey,
  required String mlsGroupId,
}) => RustLib.instance.api.crateApiAccountGroupsDeclineAccountGroup(
  accountPubkey: accountPubkey,
  mlsGroupId: mlsGroupId,
);

/// Checks if a specific group is pending for the account.
Future<bool> isAccountGroupPending({
  required String accountPubkey,
  required String mlsGroupId,
}) => RustLib.instance.api.crateApiAccountGroupsIsAccountGroupPending(
  accountPubkey: accountPubkey,
  mlsGroupId: mlsGroupId,
);

/// Checks if a specific group is accepted for the account.
Future<bool> isAccountGroupAccepted({
  required String accountPubkey,
  required String mlsGroupId,
}) => RustLib.instance.api.crateApiAccountGroupsIsAccountGroupAccepted(
  accountPubkey: accountPubkey,
  mlsGroupId: mlsGroupId,
);

/// Checks if a specific group is declined (hidden) for the account.
Future<bool> isAccountGroupDeclined({
  required String accountPubkey,
  required String mlsGroupId,
}) => RustLib.instance.api.crateApiAccountGroupsIsAccountGroupDeclined(
  accountPubkey: accountPubkey,
  mlsGroupId: mlsGroupId,
);

/// Represents the relationship between an account and an MLS group.
///
/// This struct tracks whether a user has accepted or declined a group invite.
/// When a welcome message is received, groups are auto-joined at the MLS level,
/// but the AccountGroup tracks the user's UI-level confirmation.
///
/// Confirmation states:
/// - `Pending` = auto-joined but awaiting user decision
/// - `Accepted` = user confirmed they want to see the group
/// - `Declined` = user chose to hide the group from UI
class AccountGroup {
  final PlatformInt64? id;
  final String accountPubkey;
  final String mlsGroupId;
  final bool? userConfirmation;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const AccountGroup({
    this.id,
    required this.accountPubkey,
    required this.mlsGroupId,
    this.userConfirmation,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountPubkey.hashCode ^
      mlsGroupId.hashCode ^
      userConfirmation.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountGroup &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountPubkey == other.accountPubkey &&
          mlsGroupId == other.mlsGroupId &&
          userConfirmation == other.userConfirmation &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
