// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Checks for available application updates.
///
/// This function queries the Zapstore relay to fetch the latest version
/// information for Whitenoise and compares it against the provided current version.
///
/// # Parameters
/// * `current_version` - The current application version string in semver format (e.g., "1.2.3")
///
/// # Returns
/// An `AppUpdateInfo` containing the latest version and whether an update is available.
///
/// # Errors
/// Returns an error if:
/// - Failed to connect to the Zapstore relay
/// - No version events were found
/// - The version string format is invalid
Future<AppUpdateInfo> checkForAppUpdate({required String currentVersion}) =>
    RustLib.instance.api.crateApiAppUpdateCheckForAppUpdate(
      currentVersion: currentVersion,
    );

/// Information about available application updates.
///
/// This struct contains details about the latest available version
/// and whether an update is available compared to the current version.
class AppUpdateInfo {
  /// The latest available version string (e.g., "1.2.3")
  final String version;

  /// Whether an update is available (true if latest > current)
  final bool updateAvailable;

  const AppUpdateInfo({
    required this.version,
    required this.updateAvailable,
  });

  @override
  int get hashCode => version.hashCode ^ updateAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppUpdateInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          updateAvailable == other.updateAvailable;
}
