// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'accounts.dart';
import 'error.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterNip55Callback`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `call_nip55_method`, `fmt`

/// Set the NIP-55 Flutter callback for handling external signer requests
///
/// This callback will be invoked by the Rust core when it needs to delegate
/// signing operations to an external Android signer app.
Future<void> setNip55FlutterCallback({
  required FutureOr<String> Function(String, String) callback,
}) => RustLib.instance.api.crateApiNip55SetNip55FlutterCallback(
  callback: callback,
);

/// Login with NIP-55 external signer
///
/// This method retrieves the public key from the external signer,
/// creates or finds the account, enables the NIP-55 signer, and sets up relays.
Future<Account> loginWithNip55() =>
    RustLib.instance.api.crateApiNip55LoginWithNip55();

/// Enable NIP-55 external signer for a specific account
///
/// When enabled, signing operations for this account will be delegated
/// to the external Android signer app instead of using the local key.
///
/// NOTE: This requires the account to already exist. Use `login_with_nip55`
/// for initial account creation/login.
Future<void> enableNip55Signer({required String pubkey}) =>
    RustLib.instance.api.crateApiNip55EnableNip55Signer(pubkey: pubkey);

/// Disable NIP-55 external signer for a specific account
///
/// When disabled, signing operations will use the local key again.
Future<void> disableNip55Signer({required String pubkey}) =>
    RustLib.instance.api.crateApiNip55DisableNip55Signer(pubkey: pubkey);
