// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'accounts.dart';
import 'error.dart';
import 'metadata.dart';
import 'relays.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<User> getUser({required String pubkey}) =>
    RustLib.instance.api.crateApiUsersGetUser(pubkey: pubkey);

Future<FlutterMetadata> userMetadata({required String pubkey}) =>
    RustLib.instance.api.crateApiUsersUserMetadata(pubkey: pubkey);

Future<List<Relay>> userRelays({
  required String pubkey,
  required RelayType relayType,
}) => RustLib.instance.api.crateApiUsersUserRelays(
  pubkey: pubkey,
  relayType: relayType,
);

Future<bool> userHasKeyPackage({required String pubkey}) =>
    RustLib.instance.api.crateApiUsersUserHasKeyPackage(pubkey: pubkey);

class User {
  final String pubkey;
  final FlutterMetadata metadata;
  final DateTime createdAt;
  final DateTime updatedAt;

  const User({
    required this.pubkey,
    required this.metadata,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode => pubkey.hashCode ^ metadata.hashCode ^ createdAt.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          metadata == other.metadata &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
