// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

Future<ApiResultString> npubFromPublicKey({required PublicKey publicKey}) =>
    RustLib.instance.api.crateApiUtilsNpubFromPublicKey(publicKey: publicKey);

Future<ApiResultString> npubFromHexPubkey({required String hexPubkey}) =>
    RustLib.instance.api.crateApiUtilsNpubFromHexPubkey(hexPubkey: hexPubkey);

Future<ApiResultString> hexPubkeyFromNpub({required String npub}) =>
    RustLib.instance.api.crateApiUtilsHexPubkeyFromNpub(npub: npub);

Future<ApiResultString> hexPubkeyFromPublicKey({
  required PublicKey publicKey,
}) => RustLib.instance.api.crateApiUtilsHexPubkeyFromPublicKey(
  publicKey: publicKey,
);

Future<ApiResultRelayUrl> relayUrlFromString({required String url}) =>
    RustLib.instance.api.crateApiUtilsRelayUrlFromString(url: url);

Future<String> stringFromRelayUrl({required RelayUrl relayUrl}) =>
    RustLib.instance.api.crateApiUtilsStringFromRelayUrl(relayUrl: relayUrl);

Future<ApiResultTag> tagFromVec({required List<String> vec}) =>
    RustLib.instance.api.crateApiUtilsTagFromVec(vec: vec);

Future<String> getDefaultBlossomServerUrl() =>
    RustLib.instance.api.crateApiUtilsGetDefaultBlossomServerUrl();

Future<String> groupIdToString({required GroupId groupId}) =>
    RustLib.instance.api.crateApiUtilsGroupIdToString(groupId: groupId);

Future<ApiResultGroupId> groupIdFromString({required String groupId}) =>
    RustLib.instance.api.crateApiUtilsGroupIdFromString(groupId: groupId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < GroupId >>>
abstract class ApiResultGroupId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < RelayUrl >>>
abstract class ApiResultRelayUrl implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < String >>>
abstract class ApiResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Tag >>>
abstract class ApiResultTag implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GroupId>>
abstract class GroupId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PublicKey>>
abstract class PublicKey implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RelayUrl>>
abstract class RelayUrl implements RustOpaqueInterface {}
