// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../api.dart';
import '../frb_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WelcomeState`, `_Welcome`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

Future<List<Welcome>> pendingWelcomes({required String pubkey}) =>
    RustLib.instance.api.crateApiWelcomesPendingWelcomes(pubkey: pubkey);

Future<Welcome> findWeclcomeByEventId({
  required String pubkey,
  required String welcomeEventId,
}) => RustLib.instance.api.crateApiWelcomesFindWeclcomeByEventId(
  pubkey: pubkey,
  welcomeEventId: welcomeEventId,
);

Future<void> acceptWelcome({
  required String pubkey,
  required String welcomeEventId,
}) => RustLib.instance.api.crateApiWelcomesAcceptWelcome(
  pubkey: pubkey,
  welcomeEventId: welcomeEventId,
);

Future<void> declineWelcome({
  required String pubkey,
  required String welcomeEventId,
}) => RustLib.instance.api.crateApiWelcomesDeclineWelcome(
  pubkey: pubkey,
  welcomeEventId: welcomeEventId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Welcome>>
abstract class Welcome implements RustOpaqueInterface {}
